### ISSUE TITLE
Request for raw data for Foot and Mouth Disease

### ISSUE THREAD

**Issue by taifur-bau** [road86/bahis-dash#38]
We have a request from DLS for raw data for Foot and Mouth Disease from Sep to Dec 2022 for Manikganj, Bhola, Sirajganj, and Pabna district. They will work on the data tomorrow to produce a customized report. So, if we get the data by tomorrow morning (around 10AM BDT), I think they will be able to produce the report. I got the request yesterday at 3PM and today is the Govt. holyday.

**Comment by yokat** [comment]
[230308 data_extract.xlsx](https://github.com/road86/bahis-dash/files/10919350/230308.data_extract.xlsx)

**Comment by ChasNelson1990** [comment]
Thanks @taifur-bau - we're on it. Can we make it clear to DLS though that requests for new data should not be done with such little time. It makes it difficult for us to properly plan work if we have to suddenly drop stuff.

@yokat @WaliZaman we should discuss how we add this to bahis-data or bahis-dash for the future, so that the Epi team and DLS can get this data without us.
